#!/bin/sh
# Compositing settings for xcompmgr.
# See below for more options.

# xcompmgr -cCfF -t-5 -l-5 -r4.2 -o.55 -D2 -m.80
# xcompmgr -I1 -O1 -fF -m.90 -o.85
xcompmgr -n
exit 0

# OPTIONS:
#   -d display
#          Specifies the display to manage.
#
#   -r radius
#          Specifies the blur radius for client-side shadows.
#
#   -o opacity
#          Specifies the opacity for client-side shadows.
#
#   -l left-offset
#          Specifies the left offset for client-side shadows.
#
#   -t top-offset
#          Specifies the top offset for client-side shadows.
#
#   -I fade-in-step
#          Specifies the opacity change between steps while fading in.
#
#   -O fade-out-step
#          Specifies the opacity change between steps while fading out.
#
#   -D fade-delta
#          Specifies the time (in milliseconds) between steps in a fade.
#
#   -m opacity
#          Specifies the opacity for menus. (default 1.0).
#
#   -v opacity
#          Specifies the opacity for dock/panel. (default 1.0).
#
#   -a     Automatic server-side compositing.  This instructs the server to
#          use the standard composition rules.  Useful for debugging.
#
#   -c     Client-side compositing with soft shadows and translucency  sup&#8208;
#          port.
#
#   -f     When -c is specified, enables a smooth fade effect for transient
#          windows like menus, and for all  windows  on  hide  and  restore
#          events.
#
#   -n     Simple client-side compositing.
#
#   -s     Server-side compositing with hard-edged shadows.
#
#   -C     When -c is specified, attempts to avoid painting shadows on pan&#8208;
#          els and docks.
#
#   -F     When -f is specified, also enables the fade effect when  windows
#          change their opacity, as with transset(1).
#
#   -S     Enables synchronous operation.  Useful for debugging.
