presets:
  global:
    download: ~/torrents/
     
  tv:
    series_premiere:
      path: ~/media/share/temp
      min_quality: hdtv
      max_quality: 720p
      propers: no
    series:
      hdtv:
        - Mythbusters
        - Doctor Who
        - Survivor
        - The Big Bang Theory
        - Two and a Half Men
        - How I Met Your Mother
        - Merlin
    download: ~/torrents/

  anime:
    series:
      720p:
        - Naruto Shippuuden
        - Bleach
    download: ~/torrents/   

  movies:
    limit_new: 3
    seen_movies: loose
    quality:
      min: dvdscr
      max: 720p
    imdb:
      min_score: 5.0
      min_votes: 500
      min_year: 2000
      reject_genres:
        - documentary
        - musical
        - music
        - biography
    download: ~/torrents/

feeds:
#### TV feeds:
  ezrss:
    rss: http://www.ezrss.it/feed/
    preset: tv
    
  showrss:
    rss: http://showrss.karmorra.info/rss.php?user_id=49927&hd=0&proper=0
    preset: tv
    

#### Movie feeds:
  scenetime:
    rss: http://www.scenetime.com/get_rss.php?feed=direct&user=jcmax&cat=61,47,57,1&passkey=d7d69ef7a66fb48a81b842341e3a12bb
    preset: movies

  rlslog_dvdrips:
    rlslog: http://www.rlslog.net/category/movies/dvdrip/
    preset: movies
    
  rlslog_brrips:
    rlslog: http://www.rlslog.net/category/movies/bdrip/
    preset: movies
    
  kickass_dvdrips:
    rss: http://www.kickasstorrents.com/search/dvdrip/?rss=1
    preset: movies
    
  kickass_brrips:
    rss: http://www.kickasstorrents.com/search/brrip/?rss=1
    preset: movies
 
#### Anime feeds:
  # bleach and naruto
  horrible_subs:
    rss: http://www.nyaa.eu/?page=rss&user=64513
    preset: anime
    

